# Generated by Django 5.0.3 on 2024-03-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
