# Generated by Django 5.0.3 on 2024-03-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_experience_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='whatsApp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
