# Generated by Django 5.0.3 on 2024-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aboutme_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=1, upload_to='portflio/'),
            preserve_default=False,
        ),
    ]
