# Generated by Django 5.0.3 on 2024-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default=1, upload_to='portfoilo2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default=1, upload_to='portfoilo3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(default=1, upload_to='portfoilo4'),
            preserve_default=False,
        ),
    ]
