# Generated by Django 4.2.3 on 2024-03-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_portfolio_image2_portfolio_image3_portfolio_image4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='availablefor',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='rateSkill_1to100',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='cv',
            field=models.FileField(default=1, upload_to='cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phoneNo',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
